### ISSUE TITLE
Proxy properties are ignored

### ISSUE THREAD

**Issue by Invictum** [reportportal/client-java#12]
I am using pure `client-java` `3.0.10` in my project.
And has no luck with proxy configuration. In accordance to http://reportportal.io/docs/JVM-based-clients-configuration documentation, two options should be passed `http.proxyHost` and `http.proxyPort`.

But looks like specified settings are ignored. I tried all 3 variants of passing settings with no result.
Maybe I am missed something?

**Comment by evjlobanova** [comment]
@Invictum does your question is still actual?

**Comment by asuruceanu** [comment]
This actually still valid question, so that configuring the proxy details as such described in [url](https://reportportal.io/docs/JVM-based-clients-configuration) does not work 
Ways to set up properties:
a. reportportal.properties file
http.proxyHost=localhost
http.proxyPort=45
b. command line properties 
-Dhttp.proxyHost=localhost
-Dhttp.proxyPort=45
