### ISSUE TITLE
Mechanism to bulk upload results at the end of the test case

### ISSUE THREAD

**Issue by prasadshirwadkar96** [reportportal/client-java#219]
**Is your feature request related to a problem? Please describe.**
We have many jobs running in parallel which continuously report the tests to our ReportPortal instance. This causes the server to get overloaded due to too many concurrent requests.

**Describe the solution you'd like**
We would like to understand if there is any way we can make a call to post the test results once after the test case has been run (kind of a bulk upload). In this way, we can reduce the number of requests to the server.

**Describe alternatives you've considered**
We are aware of the feature where we can upload xml/zip files containing our test results, but is there any way we can do it directly using the API client?

Version of RP: 5.7.3 (Hosted on EKS cluster)
Agent: agent-java-cucumber6 v5.1.3

**Comment by HardNorth** [comment]
@prasadshirwadkar96 No there is no such mechanism and I don't see any necessity in implementation, because server shall do the same actions for bulk uploaded tests as for regular upload: add items, calculate statistics, etc.

You should scale you server horizontally to address the case: https://reportportal.io/docs/installation-steps/ScalingUpReportPortalAPIService/
