### ISSUE TITLE
Request retry mechanism

### ISSUE THREAD

**Issue by fslev** [reportportal/client-java#248]
Hi,

I am running RP dashboard and RP client (via agent-java-cucumber6) in different network environments.
The network connection between these environments is sometimes unstable and the client connection to RP dashboard sometimes drops.
Wouldn't be useful for a retry mechanism to be in place ? 
So that in case the client cannot send data to RP, then it should retry with a number of retries configurable inside `reportportal.properties`

Thanks

**Comment by HardNorth** [comment]
@fslev We already use retry mechanism provided by OkHttp library: https://github.com/reportportal/client-java/blob/develop/src/main/java/com/epam/reportportal/service/ReportPortal.java#L574

Do you say this isn't enough? Actually retries are always two-sided coin. E.G. for status code 504 it's not clear if it's server, who didn't manage to response in time, or your request wasn't delivered due to hight network load. In the first case if a client retries the request it gets duplicate data in the system, since requests are delivered just no answer.

**Comment by fslev** [comment]
Hi,

Ok. I didn' t know that. Maybe it should be documented ?

The okhttp retry mechanism should be enough. Didn't get the chance to test this behaviour in depth.
Thanks.
